# Generated by Django 5.0.2 on 2024-05-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_korisnik_korisnicko_ime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='korisnik',
            old_name='lozinka',
            new_name='password',
        ),
    ]
