# Generated by Django 5.0.2 on 2024-05-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_lozinka_korisnik_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='korisnik',
            old_name='password',
            new_name='lozinka',
        ),
    ]
