# Generated by Django 5.0.2 on 2024-05-10 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_password_korisnik_lozinka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korisnik',
            name='lozinka',
        ),
    ]
