# Generated by Django 5.0.2 on 2024-05-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_korisnik_lozinka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='korisnicko_ime',
            field=models.CharField(max_length=100),
        ),
    ]
