# Generated by Django 5.0.2 on 2024-05-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_korisnik_korisnicko_ime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korisnik',
            name='lozinka',
        ),
    ]
