# Generated by Django 5.0.6 on 2024-05-13 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_korisnik_lozinka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zupanija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='korisnik',
            name='grad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.grad'),
        ),
        migrations.AddField(
            model_name='grad',
            name='zupanija',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.zupanija'),
        ),
        migrations.AddField(
            model_name='korisnik',
            name='zupanija',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.zupanija'),
        ),
    ]
