# Generated by Django 5.0.6 on 2024-05-13 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_grad_zupanija_korisnik_grad_grad_zupanija_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnik',
            name='oib',
            field=models.CharField(default='', max_length=11, validators=[django.core.validators.RegexValidator(message='OIB se mora sastojati od 11 znamenki.', regex='^\\d{11}$')]),
        ),
    ]
