# Generated by Django 5.0.6 on 2024-05-13 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_korisnik_grad_remove_korisnik_zupanija_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zupanija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('zupanija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.zupanija')),
            ],
        ),
    ]
