# Generated by Django 5.0.6 on 2024-05-13 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0018_customuser_delete_korisnik'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='Korisnik',
        ),
    ]
