# Generated by Django 5.0.6 on 2024-05-13 23:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_rename_customuser_korisnik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='grad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.grad'),
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='oib',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', message='OIB must be exactly 11 digits')]),
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='zupanija',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.zupanija'),
        ),
    ]
