# Generated by Django 5.0.6 on 2024-05-14 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_korisnik_options_alter_korisnik_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korisnik',
            name='grad',
        ),
        migrations.DeleteModel(
            name='Grad',
        ),
    ]
