# Generated by Django 5.0.6 on 2024-05-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_korisnik_grad_delete_grad'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnik',
            name='grad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
