# Generated by Django 5.0.6 on 2024-05-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_grad_alter_korisnik_grad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='grad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Grad',
        ),
    ]
