# Generated by Django 5.0.6 on 2024-05-15 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_kategorija_oglas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oglas',
            name='kategorija',
        ),
        migrations.RemoveField(
            model_name='oglas',
            name='korisnik',
        ),
        migrations.DeleteModel(
            name='Kategorija',
        ),
        migrations.DeleteModel(
            name='Oglas',
        ),
    ]
