# Generated by Django 5.0.6 on 2024-05-15 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_remove_oglas_kategorija_remove_oglas_korisnik_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='myapp.kategorija')),
            ],
        ),
        migrations.CreateModel(
            name='Oglas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cijena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sifra', models.IntegerField(unique=True)),
                ('naziv', models.CharField(max_length=255)),
                ('opis', models.TextField()),
                ('trajanje', models.IntegerField(choices=[(1, '1 dan'), (7, '1 tjedan'), (30, '1 mjesec')])),
                ('grad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.grad')),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zupanija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.zupanija')),
            ],
        ),
    ]
