# Generated by Django 5.0.6 on 2024-05-15 12:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_rename_parent_kategorija_roditelj'),
    ]

    operations = [
        migrations.AddField(
            model_name='oglas',
            name='kategorija',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.kategorija'),
        ),
        migrations.AlterField(
            model_name='oglas',
            name='sifra',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
