# Generated by Django 5.0.6 on 2024-05-16 16:53

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_oglas_kategorija_alter_oglas_sifra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grad',
            options={'verbose_name': 'Grad', 'verbose_name_plural': 'Gradovi'},
        ),
        migrations.AlterModelOptions(
            name='kategorija',
            options={'verbose_name': 'Kategorija', 'verbose_name_plural': 'Kategorije'},
        ),
        migrations.AlterModelOptions(
            name='oglas',
            options={'verbose_name': 'Oglas', 'verbose_name_plural': 'Oglasi'},
        ),
        migrations.AlterModelOptions(
            name='zupanija',
            options={'verbose_name': 'Zupanije', 'verbose_name_plural': 'Zupanije'},
        ),
        migrations.AlterField(
            model_name='oglas',
            name='sifra',
            field=models.CharField(default=myapp.models.Oglas.generiraj_sifru, editable=False, max_length=8, unique=True),
        ),
    ]
