# Generated by Django 5.0.6 on 2024-05-16 19:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_alter_grad_options_alter_kategorija_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oglas',
            name='datum_registracije',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
