# Generated by Django 5.0.6 on 2024-05-16 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_oglas_datum_registracije'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oglas',
            name='datum_registracije',
        ),
    ]
