# Generated by Django 5.0.6 on 2024-05-17 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_remove_oglas_datum_registracije'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slika', models.ImageField(upload_to='oglas_slike/')),
                ('oglas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slike', to='myapp.oglas')),
            ],
        ),
    ]
