# Generated by Django 5.0.6 on 2024-05-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_alter_slika_slika'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategorija',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
    ]
