# Generated by Django 5.0.6 on 2024-05-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_remove_kategorija_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategorija',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
